-- USE THE NEWLY CREATED DATABASE FOR SUBSEQUENT OPERATIONS
USE DEMOJOINS;

/*
IN MYSQL JOINS ARE USED TO COMBINE ROWS FROM TWO OR MORE TABLES BASED ON A RELATED COLUMN BETWEEN THEM. JOINS ALLOW YOU TO RETRIEVE DATA FROM MULTIPLE TABLES 
IN A SINGLE QUERY, MAKING IT EASIER TO WORK WITH RELATIONAL DATABASES.
*/