-- USE THE NEWLY CREATED DATABASE FOR SUBSEQUENT OPERATIONS
USE DEMOJOINS;

/*
IN MYSQL JOINS ARE USED TO COMBINE ROWS FROM TWO OR MORE TABLES BASED ON A RELATED COLUMN BETWEEN THEM. JOINS ALLOW YOU TO RETRIEVE DATA FROM MULTIPLE TABLES 
IN A SINGLE QUERY, MAKING IT EASIER TO WORK WITH RELATIONAL DATABASES.

1. INNER JOIN:
	- DEFINITION: THE INNER JOIN KEYWORD SELECTS RECORDS THAT HAVE MATCHING VALUES IN BOTH TABLES. 
    - PURPOSE: TO RETRIEVE ONLY THE ROWS WHERE THERE IS A MATCH IN BOTH TABLES, EFFECTIVELY FILTERING OUT NON MATCHING ROWS
    
    - EXAMPLE: 
    SELECT A.EMPLOYEEID, A.NAME, B.DEPARTMENTNAME
    FROM EMPLOYEE A 
    INNER JOIN DEPARTMENTS B ON A.DEPARTMENTID = B.DEPARTMENTID;
*/


