-- CREATE A NEW DATABASE NAME 'DEMOJOINS'
CREATE DATABASE DEMOJOINS;

-- USE THE NEWLY CREATE DATABASE FOR SUBSEQUENT OPERATIONS
USE DEMOJOINS;

-- CREATE A TABLE NAMED 'STUDENTS' WITH AN ID AND NAME
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY, -- 'ID' IS THE PRIMARY KEY AND MUST BE UNIQUE
    STUDENT_NAME VARCHAR(50) -- 'STUDENT NAME' CAN HOLD UP 50 CHARACTERS
);

-- INSERT RECORDS INTO THE 'STUDENT' TABLE
INSERT INTO STUDENT VALUES
(101, 'KIRTI'), -- ID 101 IS FOR STUDENT KIRTI
(102, 'RAVI'), -- ID 102 IS FOR STUDENT RAVI
(103, 'LAVISH'),-- ID 103 IS FOR STUDENT LAVISH
(104, 'TRISHA'); -- ID 104 IS FOR STUDENT TRISHA

-- RETRIEVE ALL RECORDS FROM THE 'STUDENT' TABLE 
SELECT * FROM STUDENT;

-- CREATE A TABLE NAMED 'COURSE' WITH AN ID AND COURSE NAME
CREATE TABLE COURSE(
	ID INT PRIMARY KEY, -- 'ID' IS THE PRIMARY KEY AND MUST BE UNIQUE
    COURSE_NAME VARCHAR(50) -- 'STUDENT NAME' CAN HOLD UP 80 CHARACTERS
);

-- INSERT RECORD INTO THE COURSE TABLE
INSERT INTO COURSE VALUES
(107, 'ENGLISH'), -- ID 107 FOR COURSE ENGLISH
(102, 'PYTHON'), -- ID 102 FOR COURSE PYTHON
(104, 'HINDI'), -- ID 104 FOR COURSE HINDI
(108, 'MATHS'); -- ID 108 FOR COURSE MATHS

-- RETRIEVE ALL RECORDS FROM THE 'COURSE' TABLE 
SELECT * FROM COURSE;

