CREATE DATABASE HEALTHCARE_SYSTEM;

USE HEALTHCARE_SYSTEM;

DROP DATABASE HEALTHCARE_SYSTEM;

-- ----------------------------------------------------------------------------TABLE - 01----------------------------------------------------------------------------------------------

CREATE TABLE PATIENTS(
PATIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL,
GENDER VARCHAR(10),
CONTACT VARCHAR(20),
ADDRESS VARCHAR(40)
);

DROP TABLE PATIENTS;

INSERT INTO PATIENTS(NAME, AGE, GENDER, CONTACT, ADDRESS)
VALUES
('SANKET SABLE', 20, 'MALE', '8291621013', 'DOMBIVALI'),
('YASH GARUD', 20, 'MALE', '9898686166', 'KALYAN'),
('ANJALI MALI', 23, 'FEMALE', '7894164684', 'AIROLI'),
('MUKASHSHAF MOMIN', 20, 'FEMALE', '8956161419', 'MUMBRA'),
('SHIVAM PATIL', 24, 'MALE', '7896954667', 'THANE'),
('NUPUR LOTEKAR', 20, 'MALE', '7715821977', 'DOMBIVALI'),
('JAYESH KUSAL', 20, 'MALE', '9874661646', 'VASHI'),
('RUSHIKESH NIRMAL', 21, 'MALE', '8979484616', 'MHAPE'),
('YASH PAWAR', 20, 'MALE', '9468946846', 'VANGANI'),
('ROHIT THORAT', 20, 'MALE', '8974886416', 'DOMBIVALI');

SELECT * FROM PATIENTS;

TRUNCATE PATIENTS;

-- GROUP BY CLAUSE
SELECT NAME 
FROM PATIENTS
ORDER BY NAME DESC;

-- LIMIT CLAUSE
SELECT NAME 
FROM PATIENTS
LIMIT 5;


-- 1. SELECT QUERIES

SELECT * FROM PATIENTS;

-- SELECT A PARTICULAR COLUMN
SELECT NAME, AGE FROM PATIENTS;

-- SELECT PATIENT BY NAME 
SELECT * FROM PATIENTS WHERE NAME = 'JAYESH KUSAL';

-- COUNT THE NUMEBR OF PATIENTS
SELECT COUNT(*) AS TOTAL_PATIENTS FROM PATIENTS;

-- SELECT PATIENTS WITH THE CONTACT CONTAINING A SPECIFIC NUMBERS
SELECT * FROM PATIENTS WHERE CONTACT LIKE '%68%';


-- 2. ALTER QUERIES

SELECT * FROM PATIENTS;

-- ADD A NEW COLUMN
ALTER TABLE PATIENTS
ADD COLUMN EMAIL VARCHAR(50) DEFAULT 'EXAMPLE123@EX.COM';

-- DROP COLUMN
ALTER TABLE PATIENTS
DROP COLUMN EMAIL;

-- RENAME THE COLUMN NAME
ALTER TABLE PATIENTS
CHANGE COLUMN CONTACT MOBILENO VARCHAR(20);

ALTER TABLE PATIENTS
CHANGE COLUMN NAME PATIENT_NAME VARCHAR(50);


SET SQL_SAFE_UPDATES = 1;
SET SQL_SAFE_UPDATES = 0;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;


-- 3. DELETE QUERIES

SELECT * FROM PATIENTS;

-- DELETE A SPECIFIC RECORD
DELETE FROM PATIENTS
WHERE PATIENT_NAME = 'YASH GARUD';

-- DELETE RECORD BASED ON CONDITION
DELETE FROM PATIENTS
WHERE AGE = 20;

-- DELETE RECORD WITH SPECIFIC NUMEBR PATTERN
DELETE FROM PATIENTS
WHERE MOBILENO LIKE '%68%';

-- DELETE RECORD WITH A SPECIFIC PATIENT_ID
DELETE FROM PATIENTS
WHERE PATIENT_ID = 0;


-- 4. RENAME QUERY

SELECT * FROM PATIENTS;

-- RENAME TABLE 
ALTER TABLE PATIENTS
RENAME TO HOSPITAL_PATIENTS;

-- RENAME THE AGE COLUMN
ALTER TABLE HOSPITAL_PATIENTS
RENAME COLUMN AGE TO PATIENT_AGE;

-- AGAIN RENAME TABLE
ALTER TABLE HOSPITAL_PATIENTS
RENAME TO PATIENTS;

-- AGAIN RENAME THE AGE COLUMN
ALTER TABLE PATIENTS
RENAME COLUMN PATIENT_AGE TO AGE;


-- UPDATE QUERY

SELECT * FROM PATIENTS;

-- UPDATE A SPECIFIC RECORD
UPDATE PATIENTS
SET AGE = 20
WHERE PATIENT_NAME LIKE '%A%';

-- UPDATE AN AGE
UPDATE PATIENTS
SET AGE = AGE + 1;


-- ----------------------------------------------------------------------------TABLE - 02----------------------------------------------------------------------------------------------

CREATE TABLE DOCTORS(
DOCTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
SPECIALITY VARCHAR(40),
PHONE VARCHAR(40),
EMAIL VARCHAR(50) UNIQUE
);

DROP TABLE DOCTORS;

INSERT INTO DOCTORS(NAME, SPECIALITY, PHONE, EMAIL)
VALUES
('AMAAN PARKAR', 'CARDIOLOGY', '(123)456-7890', 'amaanparkar123@gmail.com'),
('RAJ MALI', 'PEDIATRICS', '(123)456-7890', 'rajmali123@gmail.com'),
('ANAND TAWADE', 'ONCOLOGY', '(555)123-4567', 'anandtawade123@gmail.com'),
('SHUBHAM SURVE', 'NEUROLOGY', '(111)222-3333', 'shubhamsurve123@gmail.com'),
('SHUBHAM BHOIR', 'DERMATOLOGY', '(444)555-6666', 'shubhambhoir123@gmail.com'),
('SUMIT PAGARE', 'ORTHOPEDICS', '(777)888-9999', 'sumitpagare123@gmail.com'),
('SABRINATH NAIR', 'EMERGENCY MEDICINE', '(333)999-1111', 'sabrinathnair123@gmail.com'),
('CHETAN NEMADE', 'GASTROENTROLOGY', '(666)222-8888', 'chetannemade123@gmail.com'),
('MAHENDRA SAMANT', 'PSYCHIATRY', '(222)777-4444', 'mahendrasamant123@gmail.com'),
('SOHAM CHAUDHARY', 'OPHTHALMOLOGY', '(888)333-5555', 'sohamchaudhary123@gmail.com');

SELECT * FROM DOCTORS;

TRUNCATE DOCTORS;


-- 1. SELECT QUERY

-- SELECT A PARTICULAR COLUMN
SELECT NAME, SPECIALITY FROM DOCTORS;

-- COUNT THE NUMBER OF DOCTORS
SELECT COUNT(*) AS TOTAL_DOCTORS FROM DOCTORS;

-- SELECT DOCTOR WITH NAME
SELECT * FROM DOCTORS WHERE NAME = 'SABRINATH NAIR';

-- SELECT DATA FROM DOCTORS USING LIKE
SELECT * FROM DOCTORS WHERE NAME LIKE '%AN%';


-- 2. ALTER QUERY

SELECT * FROM DOCTORS;

-- ADD COLUMN IN TABLE
ALTER TABLE DOCTORS
ADD COLUMN GENDER VARCHAR(20) DEFAULT 'MALE';

-- CHANGE COLUMN NAME
ALTER TABLE DOCTORS
CHANGE COLUMN GENDER DOCTOR_GENDER VARCHAR(20);

-- CHANGE COLUMN NAME
ALTER TABLE DOCTORS
CHANGE COLUMN NAME DOCTOR_NAME VARCHAR(50);

-- DROP COLUMN
ALTER TABLE DOCTORS
DROP COLUMN DOCTOR_GENDER;


SET SQL_SAFE_UPDATES = 0;
SET SQL_SAFE_UPDATES = 1;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;


-- 3. DELETE QUERY

SELECT * FROM DOCTORS;

-- DELETE A SPECIFIC RECORD
DELETE FROM DOCTORS
WHERE DOCTOR_NAME = 'SHUBHAM BHOIR';

-- DELETE RECORD WITH SPECIFIC NUMBER PATTERN
DELETE FROM DOCTORS
WHERE PHONE LIKE '%456%';

-- DELETE RECORD BASED ON CONDITION
DELETE FROM DOCTORS
WHERE PHONE > '(777)888-9999';

-- DELETE A IN BETWEEN RECORD
DELETE FROM DOCTORS
WHERE DOCTOR_ID > 6 AND DOCTOR_ID < 8;


-- 4. RENAME QUERY

SELECT * FROM DOCTORS;

-- RENAME TABLE 
ALTER TABLE DOCTORS
RENAME TO HOSPITAL_DOCTORS;

-- RENAME THE NAME COLUMN
ALTER TABLE HOSPITAL_DOCTORS
RENAME COLUMN DOCTOR_NAME TO NAME;

-- RENAME TABLE AGAIN
ALTER TABLE HOSPITAL_DOCTORS
RENAME TO DOCTORS;


-- 5. UPDATE QUERY

SELECT * FROM DOCTORS;

-- UPDATE A SPECIFIC RECORD
UPDATE DOCTORS
SET PHONE = '(876)234-6543'
WHERE NAME LIKE '%MAA%';

-- UPDATE NAME
UPDATE DOCTORS
SET NAME = 'TANAY KADAM'
WHERE NAME = 'MAHENDRA SAMANT';


-- ----------------------------------------------------------------------------TABLE - 03----------------------------------------------------------------------------------------------

CREATE TABLE APPOINTMENTS(
APPOINTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT,
DOCTOR_ID INT,
DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
STATUS VARCHAR(40),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS (DOCTOR_ID)
);

DROP TABLE APPOINTMENTS;

INSERT INTO APPOINTMENTS(PATIENT_ID, DOCTOR_ID, STATUS)
VALUES
(1, 1, 'SCHEDULED'),
(2, 2, 'COMPLETED'),
(3, 3, 'SCHEDULED'),
(4, 4, 'CANCELLED'),
(5, 5, 'SCHEDULED'),
(6, 6, 'COMPLETED'),
(7, 7, 'SCHEDULED'),
(8, 8, 'SCHEDULED'),
(9, 9, 'COMPLETED'),
(10, 10, 'SCHEDULED');

SELECT * FROM APPOINTMENTS;

TRUNCATE APPOINTMENTS;


-- 1. SELECT QUERY

-- SELECT A PARTICULAR COLUMN
SELECT APPOINTMENT_ID, DATE_TIME FROM APPOINTMENTS;

-- COUNT THE NUMBER OF APPOINTMENTS
SELECT COUNT(*) AS TOTAL_APPOINTMENTS FROM APPOINTMENTS;

-- SELECT APPOINTMENT WITH ID
SELECT * FROM APPOINTMENTS WHERE APPOINTMENT_ID = 5;

-- SELECT COMPLETED STATUS APPOINTMENT 
SELECT * FROM APPOINTMENTS WHERE STATUS = 'COMPLETED';


-- 2. ALTER QUERY

SELECT * FROM APPOINTMENTS;

-- ADD COLUMN IN TABLE
ALTER TABLE APPOINTMENTS
ADD COLUMN FEES VARCHAR(20) DEFAULT '2000';

-- CHANGE COLUMN NAME
ALTER TABLE APPOINTMENTS
CHANGE COLUMN STATUS APPOINTMENT_STATUS VARCHAR(20);

-- DROP COLUMN
ALTER TABLE APPOINTMENTS
DROP COLUMN FEES;

-- AGAIN CHANGE COLUMN NAME
ALTER TABLE APPOINTMENTS
CHANGE COLUMN APPOINTMENT_STATUS STATUS VARCHAR(20);


SET SQL_SAFE_UPDATES = 0;
SET SQL_SAFE_UPDATES = 1;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;


-- 3. DELETE QUERY

SELECT * FROM APPOINTMENTS;

-- DELETE ANY RECORD
DELETE FROM APPOINTMENTS
WHERE APPOINTMENT_ID = 4;

-- DELETE RECORD WITH SPECIFIC STATUS PATTERN
DELETE FROM APPOINTMENTS
WHERE STATUS LIKE '%PLET%';

-- DELETE RECORD BASED ON CONDITION
DELETE FROM APPOINTMENTS
WHERE STATUS = 'PENDING';

-- DELETE IN BETWEEN RECORD
DELETE FROM APPOINTMENTS
WHERE APPOINTMENT_ID > 5 AND APPOINTMENT_ID < 8;


-- 4. RENAME QUERY

SELECT * FROM APPOINTMENTS;

-- RENAME TABLE 
ALTER TABLE APPOINTMENTS
RENAME TO PATIENT_APPOINTMENTS;

-- RENAME THE STATUS COLUMN
ALTER TABLE APPOINTMENTS
RENAME COLUMN STATUS TO APPOINTMENT_STATUS;

-- AGAIN RENAME STATUS COLUMN
ALTER TABLE APPOINTMENTS
RENAME COLUMN APPOINTMENT_STATUS TO STATUS;

-- RE RENAME TABLE 
ALTER TABLE PATIENT_APPOINTMENTS
RENAME TO APPOINTMENTS;


-- 5. UPDATE QUERY

SELECT * FROM APPOINTMENTS;

-- UPDATE DATE_TIME OF A SPECIFIC RECORD
UPDATE APPOINTMENTS
SET DATE_TIME = '2025-01-26'
WHERE APPOINTMENT_ID = 5;

-- UPDATE STATUS
UPDATE APPOINTMENTS
SET STATUS = 'COMPLETED'
WHERE STATUS = 'SCHEDULED';


-- ----------------------------------------------------------------------------TABLE - 04----------------------------------------------------------------------------------------------

CREATE TABLE MEDICAL_HISTORY(
HISTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT,
DIAGNOSIS VARCHAR(50),
TREATMENT VARCHAR(50),
NOTES VARCHAR(50),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

DROP TABLE MEDICAL_HISTORY;

INSERT INTO MEDICAL_HISTORY(PATIENT_ID, DIAGNOSIS, TREATMENT, NOTES)
VALUES
(1, 'HYPERTENSION', 'LISINOPRIL 10mg DAILY', 'BLOOD PRESSURE WELL CONTROLLED'),
(2, 'TYPE 2 DIABETES', 'METFORMIN 500mg TWICE DAILY', 'MONITORING BLOOD SUGAR LEVELS'),
(3, 'ASTHMA', 'ALBUTEROL INHALER AS NEEDED', 'OCCATIONAL EXACERBATIONS'),
(4, 'MIGRAINES', 'SUMATRIPTAN AS NEEDED', 'RESPONDS WELL TO MEDICATION'),
(5, 'OSTEOARTHRITIS', 'IBUPROFEN AS NEEDED', 'MANAGING PAIN WITH MEDICATION AND PT'),
(6, 'DEPRESSION', 'SERTRALINE 50mg DAILY', 'SHOWING IMPROVEMENT WITH MEDICATION'),
(7, 'SEASONAL ALLERGIES', 'LORATADINE AS NEEDED', 'SYMPTOMES CONTROLLED WITH ANTIHISTAMINES'),
(8, 'GERD', 'OMEPRAZOLE 20mg DAILY', 'MANAGING HEARTBURN SYMPTOMS'),
(9, 'HYPOTHYROIDISM', 'LEVOTHYROXINE 100mcg DAILY', 'TSH LEVEL WITHIN NORMAL RANGE'),
(10, 'ANXIETY DISORDER', 'THERAPY AND MEDICATION', 'WORKING ON COPING MECHANISM');

SELECT * FROM MEDICAL_HISTORY;

TRUNCATE MEDICAL_HISTORY;


-- 1. SELECT QUERIES

SELECT * FROM MEDICAL_HISTORY;

-- SELECT A PARTICULAR COLUMN
SELECT PATIENT_ID, TREATMENT FROM MEDICAL_HISTORY;

-- SELECT TREATMENT BY DIAGNOSIS
SELECT * FROM MEDICAL_HISTORY WHERE DIAGNOSIS = 'GERD';

-- COUNT THE NUMBER OF MEDICAL HISTORY
SELECT COUNT(*) AS TOTAL_MEDICAL_HISTORY FROM MEDICAL_HISTORY;

-- SELECT MEDICAL_HISTORY WITH NOTES CONTAINING A SPECIFIC WORD
SELECT * FROM MEDICAL_HISTORY WHERE NOTES LIKE '%CERBA%';


-- 2. ALTER QUERIES

SELECT * FROM MEDICAL_HISTORY;

-- ADD NEW COLUMN
ALTER TABLE MEDICAL_HISTORY
ADD COLUMN PATIENT_GENDER VARCHAR(20) DEFAULT 'MALE';

-- DROP COLUMN
ALTER TABLE MEDICAL_HISTORY
DROP COLUMN PATIENT_GENDER;

-- RENAME THE COLUMN
ALTER TABLE MEDICAL_HISTORY
CHANGE COLUMN DIAGNOSIS PATIENT_DIAGNOSIS VARCHAR(50);

-- AGAIN RENAME COLUMN
ALTER TABLE MEDICAL_HISTORY
CHANGE COLUMN PATIENT_DIAGNOSIS DIAGNOSIS VARCHAR(50);


SET SQL_SAFE_UPDATES = 0;
SET SQL_SAFE_UPDATES = 1;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;


-- 3. DELETE QUERIES

SELECT * FROM MEDICAL_HISTORY;

-- DELETE A SPECIFIC RECORD
DELETE FROM MEDICAL_HISTORY
WHERE DIAGNOSIS = 'ASTHMA';

-- DELETE RECORD BASED ON CONDITION
DELETE FROM MEDICAL_HISTORY
WHERE TREATMENT LIKE '%ORATA%';

-- DELETE RECORD OF A SPECIFIC PATIENT
DELETE FROM MEDICAL_HISTORY
WHERE PATIENT_ID > 5 AND PATIENT_ID < 7;

-- DELETE RECORD FROM NOTES
DELETE FROM MEDICAL_HISTORY
WHERE NOTES = 'WORKING ON COPING MECHANISM';


-- 4. RENAME QUERY

SELECT * FROM MEDICAL_HISTORY;

-- RENAME TABLE 
ALTER TABLE MEDICAL_HISTORY
RENAME TO PATIENT_MEDICAL_HISTORY;

-- RENAME COLUMN
ALTER TABLE PATIENT_MEDICAL_HISTORY
RENAME COLUMN HISTORY_ID TO PATIENT_HISTORY_ID;

-- AGAIN RENAME COLUMN
ALTER TABLE PATIENT_MEDICAL_HISTORY
RENAME COLUMN PATIENT_HISTORY_ID TO HISTORY_ID;

-- AGAIN RENAME TABLE
ALTER TABLE PATIENT_MEDICAL_HISTORY
RENAME TO MEDICAL_HISTORY;


-- 5. UPDATE QUERY

SELECT * FROM MEDICAL_HISTORY;

-- UPDATE A SPECIFIC RECORD
UPDATE MEDICAL_HISTORY
SET NOTES = 'NONE'
WHERE HISTORY_ID = 15;


-- UPDATE DIAGNOSIS
UPDATE MEDICAL_HISTORY
SET DIAGNOSIS = 'ILLNESS'
WHERE PATIENT_ID = 3;


-- ----------------------------------------------------------------------------TABLE - 05----------------------------------------------------------------------------------------------

CREATE TABLE MEDICATIONS(
MEDICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
TYPE VARCHAR(50),
PRICE VARCHAR(50),
DESCRIPTION VARCHAR(50)
);

DROP TABLE MEDICATIONS;

INSERT INTO MEDICATIONS(NAME, TYPE, PRICE, DESCRIPTION)
VALUES
('LISINOPRIL', 'ACE INHIBITOR', '$10.50', 'TREATS HIGH BLOOD PRESSURE'),
('METFORMIN', 'BIGUANIDE', '$8.75', 'MANAGES TYPE 2 DIABETES'),
('ALBUTEROL', 'BRONCHODILATOR', '$15.20', 'RELIEVES ASTHMA SYMPTOMS'),
('SUMATRIPTAN', 'TRIPTAN', '$22.99', 'TREATS MIGRAINS'),
('IBUPROFEN', 'NSAID', '$5.99', 'RELIEVES PAIN AND INFLAMMATION'),
('SERTRALINE', 'SSRI', '$12.50', 'TREATS DEPRESSION AND ANXIETY'),
('LORATADINE', 'ANTIHISTAMINE', '$7.25', 'RELIEVES ALLERGY SYMPTOMS'),
('OMEPRAZOLE', 'PPI', '$9.50', 'REDUCES STOMACH ACID'),
('LEVOTHYROXINE', 'HORMONE', '$6.80', 'TREATS HYPOTHYROIDISM'),
('ATORVASTATIN', 'STATIN', '$11.00', 'LOWERS CHOLESTEROL');

SELECT * FROM MEDICATIONS;

TRUNCATE MEDICATIONS;

-- 1. SELECT QUERY

-- SELECT A PARTICULAR COLUMN
SELECT NAME, TYPE, DESCRIPTION FROM MEDICATIONS;

-- COUNT THE NUMBER OF MEDICATIONS
SELECT COUNT(*) AS TOTAL_MEDICATIONS FROM MEDICATIONS;

-- SELECT MEDICATION WITH ID
SELECT * FROM MEDICATIONS WHERE MEDICATION_ID = 8;

-- SELECT DATA USING LIKE
SELECT * FROM MEDICATIONS
WHERE DESCRIPTION LIKE '%IG%';


-- 2. ALTER QUERY

SELECT * FROM MEDICATIONS;

-- ADD COLUMN IN TABLE
ALTER TABLE MEDICATIONS ADD COLUMN TABLET_AT_A_TIME INT DEFAULT 1;

-- CHANGE COLUMN NAME
ALTER TABLE MEDICATIONS 
CHANGE COLUMN DESCRIPTION MEDICAL_DESCRIPTION VARCHAR(100);

-- CHANGE COLUMN NAME
ALTER TABLE MEDICATIONS
CHANGE COLUMN MEDICAL_DESCRIPTION DESCRIPTION VARCHAR(100);

-- DROP COLUMN
ALTER TABLE MEDICATIONS DROP COLUMN TABLET_AT_A_TIME;


SET SQL_SAFE_UPDATES = 0;
SET SQL_SAFE_UPDATES = 1;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;


-- 3. DELETE QUERY

SELECT * FROM MEDICATIONS;

-- DELETE ANY RECORD
DELETE FROM MEDICATIONS
WHERE NAME = 'ALBUTEROL';

-- DELETE RECORD WITH SPECIFIC PATTERN
DELETE FROM MEDICATIONS
WHERE DESCRIPTION LIKE '%IG%';

-- DELETE RECORD USING ID
DELETE FROM MEDICATIONS
WHERE MEDICATION_ID = 5;

-- DELETE RECORD USING BETWEEN CLAUSE
DELETE FROM MEDICATIONS
WHERE MEDICATION_ID BETWEEN 3 AND 8;


-- 4. RENAME QUERY

SELECT * FROM MEDICATIONS;

SELECT * FROM HOSPITAL_MEDICATIONS;

-- RENAME TABLE
ALTER TABLE MEDICATIONS
RENAME TO HOSPITAL_MEDICATIONS;

ALTER TABLE HOSPITAL_MEDICATIONS
RENAME TO MEDICATIONS;

-- RENAME COLUMN
ALTER TABLE MEDICATIONS
RENAME COLUMN TYPE TO MEDICATION_TYPE;

ALTER TABLE MEDICATIONS
RENAME COLUMN MEDICATION_TYPE TO TYPE;


-- 5. UPDATE QUERY

SELECT * FROM MEDICATIONS;

-- UPDATE NAME 
UPDATE MEDICATIONS
SET NAME = 'PARACETAMOL'
WHERE MEDICATION_ID = 10;

UPDATE MEDICATIONS
SET TYPE = 'PAIN KILLER'
WHERE NAME = 'PARACETAMOL';


-- ----------------------------------------------------------------------------TABLE - 06----------------------------------------------------------------------------------------------

CREATE TABLE PRESCRIPTIONS(
PRESCRIPTION_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT,
MEDICATION_ID INT,
DATE_PROVIDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DOSAGE VARCHAR(50),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATIONS(MEDICATION_ID)
);

DROP TABLE PRESCRIPTIONS;

INSERT INTO PRESCRIPTIONS(PATIENT_ID, MEDICATION_ID, DOSAGE)
VALUES
(1, 1, '10mg DAILY'),
(2, 2, '500mg TWICE DAILY'),
(3, 3, 'AS NEEDED'),
(4, 4, 'AS NEEDED'),
(5, 5, '400mg EVERY 6 HOURS'),
(6, 6, '50mg DAILY'),
(7, 7, '10mg DAILY'),
(8, 8, '20mg DAILY'),
(9, 9, '100mcg DAILY'),
(10, 10, '20mg DAILY');

SELECT * FROM PRESCRIPTIONS;

TRUNCATE PRESCRIPTIONS;


-- ----------------------------------------------------------------------------TABLE - 07----------------------------------------------------------------------------------------------

CREATE TABLE BILLS(
BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT,
TOTAL_AMOUNT VARCHAR(10),
PAYMENT_STATUS VARCHAR(20) ,
DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

DROP TABLE BILLS;

INSERT INTO BILLS(PATIENT_ID, TOTAL_AMOUNT, PAYMENT_STATUS)
VALUES
(1, '$150.00', 'PAID'),
(2, '$75.50', 'PENDING'),
(3, '$225.75', 'PAID'),
(4, '$50.00', 'PAID'),
(5, '$100.25', 'PENDING'),
(6, '$180.00', 'PAID'),
(7, '$90.50', 'PENDING'),
(8, '$120.75', 'PAID'),
(9, '$60.00', 'PAID'),
(10, '$200.50', 'PENDING');

SELECT * FROM BILLS;

TRUNCATE BILLS;

-- ----------------------------------------------------------------------------TABLE - 08----------------------------------------------------------------------------------------------

CREATE TABLE STAFF(
STAFF_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(40),
ROLE VARCHAR(20),
CONTACT VARCHAR(12),
SHIFT VARCHAR(40)
);

DROP TABLE STAFF;

INSERT INTO STAFF(NAME, ROLE, CONTACT, SHIFT)
VALUES
('DR.RAJESH DESHMUKH', 'HEAD DOCTOR', '9876543210', 'DAY'),
('SEEMA PATIL', 'NURSE', '8765432109', 'NIGHT'),
('VIJAY KADAM', 'RECEPTIONIST', '7654321098', 'DAY'),
('ANJALI PAWAR', 'LAB TECHNICIAN', '8989654458', 'ROTATING'),
('SURESH SHINDE', 'PHARMACIST', '5432109876', 'DAY'),
('MAYA JADHAV', 'NURSE', '4321098765', 'NIGHT'),
('KIRAN MORE', 'SECURITY GUARD', '3210987654', 'NIGHT'),
('PRIYA DESAI', 'ADMIN ASSISTANT', '2109876543', 'DAY'),
('ROHAN JOSHI', 'WARD BOY', '1098765432', 'ROTATING'),
('NEHA CHAVHAN', 'COUNSELOR', '9087654321', 'DAY');

SELECT * FROM STAFF;

TRUNCATE STAFF;

-- ----------------------------------------------------------------------------TABLE - 09----------------------------------------------------------------------------------------------

CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
LOCATION VARCHAR(20),
PHONE VARCHAR(20)
);

DROP TABLE DEPARTMENTS;

INSERT INTO DEPARTMENTS(NAME, LOCATION, PHONE)
VALUES
('CARDIOLOGY', '2nd FLOOR', '(123)555-1212'),
('ONCOLOGY', '3rd FLOOR', '(123)555-1313'),
('PEDIATRICS', '1st FLOOR', '(123)555-1414'),
('EMERGENCY ROOM', 'GROUD FLOOR', '(123)555-9111'),
('RADIOLOGY', 'BASEMENT', '(123)555-1515'),
('SURGERY', '4th FLOOR', '(123)555-1616'),
('NEUROLOGY', '3rd FLOOR', '(123)555-1717'),
('PHARMACY', 'GROUND FLOOR', '(123)555-1818'),
('LABORATORY', 'BASEMENT', '(123)555-1919'),
('OUTPATIENT CLINIC', '1st FLOOR', '(123)555-2020');

SELECT * FROM DEPARTMENTS;

TRUNCATE DEPARTMENTS;

-- ----------------------------------------------------------------------------TABLE - 10----------------------------------------------------------------------------------------------

CREATE TABLE FACILITIES(
FACULITY_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
TYPE VARCHAR(50),
COST VARCHAR(50),
AVAILABILITY_STATUS VARCHAR(50)
);

DROP TABLE FACILITIES;

INSERT INTO FACILITIES(NAME, TYPE, COST, AVAILABILITY_STATUS)
VALUES
('MRI MACHINE', 'IMAGING', '$500/SCAN', 'AVAILABLE'),
('X-RAY MACHINE', 'IMAGING', '$100/SCAN', 'AVAILABLE'),
('CT SCANNER', 'IMAGING', '$300/SCAN', 'AVAILABLE'),
('OPERATING ROOM 1', 'SURGICAL', '$1500/HOUR', 'AVAILABLE'),
('OPERATING ROOM 2', 'SURGICAL', '$1500/HOUR', 'UNDER MAINTAINANCE'),
('INTENSIVE CARE UNIT BED 1', 'CRITICAL CARE', '$2000/DAY', 'AVAILABLE'),
('INTENSIVE CARE UNIT BED 2', 'CRITICAL CARE', '$2000/DAY', 'OCCUPIED'),
('PHYSICAL THERAPY GYM', 'REHABILITATION', '$50/SESSION', 'AVAILABLE'),
('LABORATORY EQUIPMENT SET', 'LABORATORY', 'N/A', 'AVAILABLE'),
('ULTRASOUND MACHINE', 'IMAGING', '$200/SCAN', 'AVAILABLE');

SELECT * FROM FACILITIES;

TRUNCATE FACILITIES; 